In [ ]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

### Creating a Manual Dataset for Apriori

In [ ]:
dataset = [
    ['milk', 'bread', 'butter', 'eggs'],
    ['milk', 'bread', 'butter'],
    ['milk', 'yogurt'],
    ['bread', 'butter', 'jam'],
    ['milk', 'bread', 'yogurt', 'eggs'],
    ['bread', 'cheese'],
    ['milk', 'bread', 'butter']
]
display(dataset)

[['milk', 'bread', 'butter', 'eggs'],
 ['milk', 'bread', 'butter'],
 ['milk', 'yogurt'],
 ['bread', 'butter', 'jam'],
 ['milk', 'bread', 'yogurt', 'eggs'],
 ['bread', 'cheese'],
 ['milk', 'bread', 'butter']]

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

display(df.head())

   bread  butter  cheese   eggs    jam   milk  yogurt
0   True    True   False   True  False   True   False
1   True    True   False  False  False   True   False
2  False   False   False  False  False   True    True
3   True    True   False  False   True  False   False
4   True   False   False   True  False   True    True

In [ ]:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
display(frequent_itemsets)

    support         itemsets
0  0.857143          (bread)
1  0.571429         (butter)
2  0.714286           (milk)
3  0.571429  (bread, butter)
4  0.571429    (bread, milk)

In [ ]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
display(rules)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(butter),(bread),0.571429,0.857143,0.571429,1.000000,1.166667,1.0,0.081633,inf,0.333333,0.666667,1.000000,0.833333
1,(bread),(butter),0.857143,0.571429,0.571429,0.666667,1.166667,1.0,0.081633,1.285714,1.000000,0.666667,0.222222,0.833333
2,(bread),(milk),0.857143,0.714286,0.571429,0.666667,0.933333,1.0,-0.040816,0.857143,-0.333333,0.571429,-0.166667,0.733333
3,(milk),(bread),0.714286,0.857143,0.571429,0.800000,0.933333,1.0,-0.040816,0.714286,-0.200000,0.571429,-0.400000,0.733333

## FP GROWTH

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

frequent_itemsets_fpgrowth = fpgrowth(df, min_support=0.5, use_colnames=True)
display(frequent_itemsets_fpgrowth)

    support         itemsets
0  0.857143          (bread)
1  0.714286           (milk)
2  0.571429         (butter)
3  0.571429    (bread, milk)
4  0.571429  (butter, bread)